import Employee.Doctor;
import Employee.Employee;
import Employee.Nurse;
import Employee.Therapist;

/**
 *
 * @author elif
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TherapistPromoButton = new javax.swing.JButton();
        DoctorPromoLabel = new javax.swing.JLabel();
        TherapistPromoField = new javax.swing.JTextField();
        DoctorPromoButton1 = new javax.swing.JButton();
        DoctorPromoField = new javax.swing.JTextField();
        NursePromoField = new javax.swing.JTextField();
        NursePromoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Employee Promo System");

        TherapistPromoButton.setText("Therapist");
        TherapistPromoButton.setActionCommand("");
        TherapistPromoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TherapistPromoButtonActionPerformed(evt);
            }
        });

        DoctorPromoButton1.setText("Doctor");
        DoctorPromoButton1.setActionCommand("");
        DoctorPromoButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorPromoButton1ActionPerformed(evt);
            }
        });

        NursePromoButton.setText("Nurse");
        NursePromoButton.setActionCommand("");
        NursePromoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NursePromoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TherapistPromoButton)
                        .addGap(133, 133, 133)
                        .addComponent(NursePromoButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(DoctorPromoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(DoctorPromoField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(TherapistPromoField, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(NursePromoField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(DoctorPromoButton1)
                    .addContainerGap(524, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TherapistPromoButton)
                    .addComponent(NursePromoButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TherapistPromoField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NursePromoField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorPromoField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(DoctorPromoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(85, 85, 85)
                    .addComponent(DoctorPromoButton1)
                    .addContainerGap(158, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * By pressing the buttons of the relevant occupational groups, promotion
     * details/transactions related to them are displayed.
     */
    private void TherapistPromoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TherapistPromoButtonActionPerformed
        // TODO add your handling code here:
        Employee therapist = new Therapist();
        double therapistPromo;
        therapistPromo = therapist.pro.findPromo();
        TherapistPromoField.setText("Therapist promo is: " + therapistPromo);
    }//GEN-LAST:event_TherapistPromoButtonActionPerformed

    private void DoctorPromoButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorPromoButton1ActionPerformed
        // TODO add your handling code here:
        Employee doctor = new Doctor();
        double doctorPromo;
        doctorPromo = doctor.pro.findPromo();
        DoctorPromoField.setText("Doctor promo is: " + doctorPromo);
    }//GEN-LAST:event_DoctorPromoButton1ActionPerformed

    private void NursePromoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NursePromoButtonActionPerformed
        // TODO add your handling code here:
        Employee nurse = new Nurse();
        double nursePromo;
        nursePromo = nurse.pro.findPromo();
        NursePromoField.setText("Nurse promo is: " + nursePromo);
    }//GEN-LAST:event_NursePromoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorPromoButton1;
    private javax.swing.JTextField DoctorPromoField;
    private javax.swing.JLabel DoctorPromoLabel;
    private javax.swing.JButton NursePromoButton;
    private javax.swing.JTextField NursePromoField;
    private javax.swing.JButton TherapistPromoButton;
    private javax.swing.JTextField TherapistPromoField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
